-- STE-11 (C7) — the PII vault.
--
-- One rule shapes this whole schema: the chain gets `participant_hash` and
-- nothing else, so everything that could identify a person lives here, encrypted,
-- and never leaves. Columns that hold a person are `bytea` holding an
-- AES-256-GCM envelope (be/src/crypto/envelope.ts); there is deliberately no
-- text column anywhere that a `SELECT *` could reveal a name from.

CREATE TABLE participants (
    -- Generated by the application, not the database, because the id is the
    -- AAD that binds each ciphertext to this row — it has to exist before the
    -- values are encrypted.
    id                  uuid PRIMARY KEY,

    -- Encrypted PII. bytea, never text. The envelope carries its own key id,
    -- so rotation does not need a column here.
    name_enc            bytea NOT NULL,
    national_id_enc     bytea NOT NULL,
    emergency_contact_enc bytea NOT NULL,

    -- Secrets that are not PII but are still secrets: the salt proves the hash,
    -- the TOTP secret mints check-in codes. Both are 32 raw bytes, both are
    -- shown to the runner exactly once, and both stay here because the roster
    -- bundle (STE-16) needs the TOTP secret at race time.
    salt                bytea NOT NULL,
    totp_secret         bytea NOT NULL,

    -- The only value that also exists on-chain. Not unique: the same person may
    -- enter several events, and each entry gets its own salt, so in practice
    -- these differ — but uniqueness is not a property we can promise, and a
    -- constraint that is almost always true is a production incident waiting
    -- for the collision.
    participant_hash    bytea NOT NULL,

    -- Which event and category this entry is for. Plain integers: they are
    -- public on-chain data.
    event_id            integer NOT NULL CHECK (event_id >= 0),
    category_id         integer NOT NULL CHECK (category_id >= 0),

    -- The runner's Stellar account. Public by definition — it is on every
    -- transaction they sign — and it is what authenticates requests about this
    -- row.
    runner_address      text NOT NULL CHECK (runner_address ~ '^G[A-Z2-7]{55}$'),

    -- Filled in by /confirm once `enter` has landed on-chain. NULL until then,
    -- which is the honest representation of "submitted but not yet entered".
    token_id            integer CHECK (token_id >= 0),
    enter_tx_hash       text CHECK (enter_tx_hash ~ '^[0-9a-f]{64}$'),
    confirmed_at        timestamptz,

    created_at          timestamptz NOT NULL DEFAULT now(),

    -- token_id, its transaction and its timestamp arrive together or not at
    -- all. Allowing two of the three would let a row claim to be on-chain
    -- without saying which transaction put it there.
    CONSTRAINT confirmation_is_all_or_nothing CHECK (
        (token_id IS NULL AND enter_tx_hash IS NULL AND confirmed_at IS NULL)
        OR (token_id IS NOT NULL AND enter_tx_hash IS NOT NULL AND confirmed_at IS NOT NULL)
    )
);

-- One PII row per on-chain record. The record is the thing that exists once;
-- two vault rows pointing at one token_id would mean two people claiming the
-- same bib. Partial, so the unconfirmed rows (all NULL) do not collide.
CREATE UNIQUE INDEX participants_token_id_key ON participants (token_id)
    WHERE token_id IS NOT NULL;

-- The lookup the entry flow does: "what has this runner submitted for this
-- event?" — used to find the row to confirm.
CREATE INDEX participants_runner_event_idx ON participants (runner_address, event_id);

-- The lookup the scanner path will do (STE-16): hash -> record.
CREATE INDEX participants_hash_idx ON participants (participant_hash);
