/**
 * STE-40 — the SDK's announcement helpers, against the shared vectors in
 * `schema/announcement-v1.vectors.json`.
 *
 * The backend is tested against the same file, and the file was generated by a
 * third, independent implementation. So a browser verifying an announcement
 * with this package and the server that accepted it agree on the exact bytes.
 */
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import {
  ANNOUNCEMENT_HEADER,
  announcementBodySha256,
  announcementMessage,
  verifyAnnouncement,
} from "../src/index.js";

interface VectorCase {
  name: string;
  input: {
    network_passphrase: string;
    event_registry: string;
    event_id: number;
    published_at: string;
    body: string;
  };
  body_sha256: string;
  message: string;
  signer: string;
  signature_ed25519: string;
  signature_sep53: string;
}

const vectors = JSON.parse(
  readFileSync(new URL("../schema/announcement-v1.vectors.json", import.meta.url), "utf8"),
) as { cases: VectorCase[]; negative: { other_signer: string } };

const fieldsOf = (c: VectorCase) => ({
  networkPassphrase: c.input.network_passphrase,
  eventRegistry: c.input.event_registry,
  eventId: c.input.event_id,
  publishedAt: c.input.published_at,
  body: c.input.body,
});

describe("announcementMessage", () => {
  it.each(vectors.cases.map((c) => [c.name, c] as const))("builds the vector's exact message: %s", (_n, c) => {
    expect(announcementMessage(fieldsOf(c))).toBe(c.message);
    expect(announcementBodySha256(c.input.body)).toBe(c.body_sha256);
    expect(c.message.split("\n")[0]).toBe(ANNOUNCEMENT_HEADER);
  });

  it.each([
    ["without milliseconds", "2026-09-16T00:00:00Z"],
    ["with an offset", "2026-09-16T07:00:00.000+07:00"],
    ["as a date only", "2026-09-16"],
  ])("refuses a publishedAt %s, since the signed text must be unambiguous", (_what, publishedAt) => {
    const [first] = vectors.cases as [VectorCase];
    expect(() => announcementMessage({ ...fieldsOf(first), publishedAt })).toThrow(TypeError);
  });

  it("refuses a negative or fractional event id", () => {
    const [first] = vectors.cases as [VectorCase];
    expect(() => announcementMessage({ ...fieldsOf(first), eventId: -1 })).toThrow(TypeError);
    expect(() => announcementMessage({ ...fieldsOf(first), eventId: 1.5 })).toThrow(TypeError);
  });
});

describe("verifyAnnouncement", () => {
  it.each(vectors.cases.map((c) => [c.name, c] as const))("accepts both schemes: %s", (_n, c) => {
    expect(verifyAnnouncement({ ...fieldsOf(c), signer: c.signer, signature: c.signature_ed25519 })).toEqual({
      valid: true,
      scheme: "ed25519",
    });
    expect(verifyAnnouncement({ ...fieldsOf(c), signer: c.signer, signature: c.signature_sep53 })).toEqual({
      valid: true,
      scheme: "sep53",
    });
  });

  const [first] = vectors.cases as [VectorCase];
  const good = { ...fieldsOf(first), signer: first.signer, signature: first.signature_sep53 };

  it.each([
    ["a different body", { ...good, body: `${good.body}!` }],
    ["another event", { ...good, eventId: good.eventId + 1 }],
    ["another registry", { ...good, eventRegistry: "CCVW7WVCPHLPQASIDE6DLT7P7YCE3VUNGRCWDVKEA7XAD56LX22HA6NW" }],
    ["another network", { ...good, networkPassphrase: "Public Global Stellar Network ; September 2015" }],
    ["another signer", { ...good, signer: vectors.negative.other_signer }],
    ["a truncated signature", { ...good, signature: Buffer.from(good.signature, "base64").subarray(0, 63).toString("base64") }],
    ["a malformed publishedAt", { ...good, publishedAt: "2026-09-20" }],
    ["a malformed signer", { ...good, signer: "GNOTAKEY" }],
  ])("is invalid for %s, and never throws", (_what, announcement) => {
    expect(verifyAnnouncement(announcement)).toEqual({ valid: false });
  });
});
