/**
 * STE-40 — signed event announcements, the message format and its verification.
 *
 * An event document is frozen by its hash once published (STE-34), so a race
 * that moves venue, extends registration (STE-45) or raises a quota (STE-55)
 * says so in an **announcement** beside the document, never by editing it
 * (`docs/WEB_APP_IA.md` §6.1).
 *
 * What makes an announcement worth anything is that **anyone can re-verify it
 * without trusting this service**. So the organiser does not sign a login
 * nonce: they sign the announcement itself, in this exact form.
 *
 *     Sterun announcement v1
 *     network: <network passphrase>
 *     event_registry: <EventRegistry contract id>
 *     event_id: <u32>
 *     published_at: <YYYY-MM-DDTHH:MM:SS.sssZ>
 *     body_sha256: <sha256 of the UTF-8 body, lowercase hex>
 *
 * Lines joined by LF, no trailing newline. The network and the registry are in
 * the message so a testnet announcement can never be replayed as a mainnet one,
 * or against a different registry where `event_id` names another race. The
 * body is hashed rather than inlined so it may contain newlines of its own.
 *
 * The same format is implemented in `@sterunxyz/sdk` (`announcementMessage`,
 * `verifyAnnouncement`), and both are pinned to
 * `sdk/schema/announcement-v1.vectors.json`, generated by a third, independent
 * implementation. A change here that is not a new version breaks every
 * announcement already published.
 */
import { createHash } from "node:crypto";
import { Keypair } from "@stellar/stellar-sdk";

export const ANNOUNCEMENT_HEADER = "Sterun announcement v1";

/** `published_at` is signed as text, so exactly one spelling of a time is valid. */
export const PUBLISHED_AT_PATTERN = "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\.[0-9]{3}Z$";

export type SignatureScheme = "ed25519" | "sep53";

export interface AnnouncementFields {
  networkPassphrase: string;
  eventRegistry: string;
  eventId: number;
  publishedAt: string;
  body: string;
}

export const bodySha256 = (body: string): Buffer => createHash("sha256").update(body, "utf8").digest();

export function announcementMessage(fields: AnnouncementFields): string {
  return [
    ANNOUNCEMENT_HEADER,
    `network: ${fields.networkPassphrase}`,
    `event_registry: ${fields.eventRegistry}`,
    `event_id: ${fields.eventId}`,
    `published_at: ${fields.publishedAt}`,
    `body_sha256: ${bodySha256(fields.body).toString("hex")}`,
  ].join("\n");
}

/**
 * Which scheme, if any, makes `signature` a valid signature by `signer` over the
 * announcement. `null` for a wrong signature, a malformed key or a signature of
 * the wrong length: callers do not learn which part was wrong.
 *
 * Two schemes for the same reason the login accepts two: a script signs the
 * message bytes directly, and a browser wallet can only sign through SEP-53.
 */
export function verifyAnnouncementSignature(
  message: string,
  signer: string,
  signature: Buffer,
): SignatureScheme | null {
  if (signature.length !== 64) return null;
  try {
    const key = Keypair.fromPublicKey(signer);
    if (key.verify(Buffer.from(message, "utf8"), signature)) return "ed25519";
    if (key.verifyMessage(message, signature)) return "sep53";
    return null;
  } catch {
    return null;
  }
}
