/**
 * Countries, provinces and cities, from a file rather than from an API.
 *
 * Generated by `scripts/build-places.mjs` and committed. The reasoning is in
 * that script's header, and the short version is: a select that depends on
 * somebody else's uptime cannot be filled in on their bad day, the free tiers
 * of the hosted versions are three requests per form fill against a hundred a
 * day, and these names end up in an event document that is hashed and can never
 * be edited, so we want to know exactly which version of the data wrote them.
 *
 * Cities exist for one country. Worldwide cities are a 46 MB file, the pilot is
 * Indonesian, and a city list that covers one country honestly is worth more
 * than one that half-covers all of them. Everywhere else the city is typed.
 */
import places from "@/data/places.json";

export interface Country {
  iso2: string;
  name: string;
}

export interface Province {
  id: number;
  name: string;
}

const data = places as {
  attribution: string;
  generatedAt: string;
  citiesFor: string;
  countries: Country[];
  states: Record<string, Province[]>;
  cities: Record<string, string[]>;
};

/** ODbL requires this to be shown wherever the data is. */
export const PLACES_ATTRIBUTION = data.attribution;

export const countries: readonly Country[] = data.countries;

/** Provinces of a country, or an empty list for one with none in the data. */
export function provincesOf(iso2: string): readonly Province[] {
  return data.states[iso2] ?? [];
}

/**
 * Cities of a province, or an empty list. Empty means "type it", not "there
 * are none", which is why callers fall back to a text field rather than
 * blocking.
 */
export function citiesOf(provinceId: number | null): readonly string[] {
  if (provinceId === null) return [];
  return data.cities[String(provinceId)] ?? [];
}

/** Whether this country has a city list at all. */
export function hasCities(iso2: string): boolean {
  return iso2 === data.citiesFor;
}

export function countryName(iso2: string): string | null {
  return data.countries.find((country) => country.iso2 === iso2)?.name ?? null;
}

export function provinceName(iso2: string, id: number | null): string | null {
  if (id === null) return null;
  return provincesOf(iso2).find((province) => province.id === id)?.name ?? null;
}
