/**
 * Countries, provinces and cities, from a file rather than from an API.
 *
 * Generated by `scripts/build-places.mjs` and committed. The reasoning is in
 * that script's header, and the short version is: a select that depends on
 * somebody else's uptime cannot be filled in on their bad day, the free tiers
 * of the hosted versions are three requests per form fill against a hundred a
 * day, and these names end up in an event document that is hashed and can never
 * be edited, so we want to know exactly which version of the data wrote them.
 *
 * Countries and provinces are in this bundle because nothing can be picked
 * before them. Cities are not: they are one static file per country under
 * `public/places/`, fetched when a country is chosen. Names alone for the whole
 * world are 2.1 MB across 223 files, so shipping them all would cost every
 * visitor 2.1 MB to read a list of races, while fetching one costs the
 * organiser filling in the form about 10 KB.
 *
 * Nothing here caches. `useCities` holds the result in the query cache the rest
 * of the app already uses, and a fetch layer that also caches is a second
 * cache to reason about for no gain.
 */
import places from "@/data/places.json";

export interface Country {
  iso2: string;
  name: string;
}

export interface Province {
  id: number;
  name: string;
}

/** Province id to the city names in it. The shape of one `public/places` file. */
export type CitiesByProvince = Record<string, readonly string[]>;

const data = places as {
  attribution: string;
  generatedAt: string;
  countries: Country[];
  states: Record<string, Province[]>;
  hasCities: string[];
};

const COUNTRIES_WITH_CITIES = new Set(data.hasCities);

/** ODbL requires this to be shown wherever the data is. */
export const PLACES_ATTRIBUTION = data.attribution;

export const countries: readonly Country[] = data.countries;

/** Provinces of a country, or an empty list for one with none in the data. */
export function provincesOf(iso2: string): readonly Province[] {
  return data.states[iso2] ?? [];
}

/** Whether this country has a city file worth fetching. 223 of 250 do. */
export function hasCities(iso2: string): boolean {
  return COUNTRIES_WITH_CITIES.has(iso2);
}

/**
 * One country's cities, or an empty map.
 *
 * Empty always means "type the city", never "this country has no cities", and
 * every way this can go wrong ends there: no file, a refused request, a body
 * that is not the shape it should be. A dropped list costs an organiser a
 * dropdown; a thrown error would cost them the form, and the form is the thing
 * that must not break.
 */
export async function fetchCities(iso2: string): Promise<CitiesByProvince> {
  if (!hasCities(iso2)) return {};

  try {
    const response = await fetch(`/places/${iso2}.json`);
    if (!response.ok) return {};
    const body: unknown = await response.json();
    if (typeof body !== "object" || body === null || Array.isArray(body)) return {};
    return body as CitiesByProvince;
  } catch {
    return {};
  }
}

export function countryName(iso2: string): string | null {
  return data.countries.find((country) => country.iso2 === iso2)?.name ?? null;
}

export function provinceName(iso2: string, id: number | null): string | null {
  if (id === null) return null;
  return provincesOf(iso2).find((province) => province.id === id)?.name ?? null;
}
