/**
 * STE-40 — the announcement message and its signature, against the shared
 * vectors in `sdk/schema/announcement-v1.vectors.json`.
 *
 * That file was generated by a third, independent implementation, and
 * `@sterunxyz/sdk` is tested against it too. So this backend and every client
 * built on the SDK agree on the exact bytes an organiser signs, or a test fails.
 */
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import {
  ANNOUNCEMENT_HEADER,
  announcementMessage,
  bodySha256,
  verifyAnnouncementSignature,
} from "../src/announcements.js";

interface VectorCase {
  name: string;
  input: {
    network_passphrase: string;
    event_registry: string;
    event_id: number;
    published_at: string;
    body: string;
  };
  body_sha256: string;
  message: string;
  signer: string;
  signature_ed25519: string;
  signature_sep53: string;
}

const vectors = JSON.parse(
  readFileSync(new URL("../../sdk/schema/announcement-v1.vectors.json", import.meta.url), "utf8"),
) as { cases: VectorCase[]; negative: { other_signer: string } };

const fieldsOf = (c: VectorCase) => ({
  networkPassphrase: c.input.network_passphrase,
  eventRegistry: c.input.event_registry,
  eventId: c.input.event_id,
  publishedAt: c.input.published_at,
  body: c.input.body,
});
const b64 = (s: string) => Buffer.from(s, "base64");

describe("the announcement message (format v1)", () => {
  it("has at least two vectors, one with non-ASCII text and a line break", () => {
    expect(vectors.cases.length).toBeGreaterThanOrEqual(2);
    const nonAscii = (s: string) => [...s].some((ch) => (ch.codePointAt(0) as number) > 0x7f);
    expect(vectors.cases.some((c) => c.input.body.includes("\n") && nonAscii(c.input.body))).toBe(true);
  });

  it.each(vectors.cases.map((c) => [c.name, c] as const))("builds exactly the vector's message: %s", (_n, c) => {
    expect(announcementMessage(fieldsOf(c))).toBe(c.message);
    expect(bodySha256(c.input.body).toString("hex")).toBe(c.body_sha256);
    expect(c.message.startsWith(`${ANNOUNCEMENT_HEADER}\n`)).toBe(true);
    expect(c.message.endsWith("\n")).toBe(false);
  });
});

describe("verifying a signature", () => {
  it.each(vectors.cases.map((c) => [c.name, c] as const))("accepts both schemes: %s", (_n, c) => {
    expect(verifyAnnouncementSignature(c.message, c.signer, b64(c.signature_ed25519))).toBe("ed25519");
    expect(verifyAnnouncementSignature(c.message, c.signer, b64(c.signature_sep53))).toBe("sep53");
  });

  const [first] = vectors.cases as [VectorCase];
  const signature = b64(first.signature_sep53);

  it.each([
    ["a different body", { ...fieldsOf(first), body: `${first.input.body}!` }],
    ["another event", { ...fieldsOf(first), eventId: first.input.event_id + 1 }],
    ["another registry", { ...fieldsOf(first), eventRegistry: "CCVW7WVCPHLPQASIDE6DLT7P7YCE3VUNGRCWDVKEA7XAD56LX22HA6NW" }],
    ["another network", { ...fieldsOf(first), networkPassphrase: "Public Global Stellar Network ; September 2015" }],
    ["a different time", { ...fieldsOf(first), publishedAt: "2026-09-20T07:05:00.001Z" }],
  ])("refuses the signature over %s", (_what, fields) => {
    expect(verifyAnnouncementSignature(announcementMessage(fields), first.signer, signature)).toBeNull();
  });

  it("refuses the right signature under another signer", () => {
    expect(verifyAnnouncementSignature(first.message, vectors.negative.other_signer, signature)).toBeNull();
  });

  it("refuses a signature of the wrong length or a malformed signer, without throwing", () => {
    expect(verifyAnnouncementSignature(first.message, first.signer, signature.subarray(0, 63))).toBeNull();
    expect(verifyAnnouncementSignature(first.message, "GNOTAKEY", signature)).toBeNull();
  });
});
